import struct
import csv
from collections import defaultdict
import telemetry_record_pb2  # This module is auto-generated by the build block

def run_flume_aggregation():
    print("====== [FlumeLite Engine: Python Runtime] ======")
    
    log_files = ["worker_node_0_telemetry.bin"]
    global_aggregates = defaultdict(lambda: {"total_value": 0.0, "count": 0})

    for file_path in log_files:
        try:
            with open(file_path, "rb") as f:
                while True:
                    # Read the 4-byte size prefix encoded by the C++ agent
                    size_bytes = f.read(4)
                    if not size_bytes or len(size_bytes) < 4:
                        break
                    
                    size = struct.unpack("I", size_bytes)[0]
                    buffer = f.read(size)
                    if len(buffer) < size:
                        break
                    
                    # Unpack the high-performance batch record
                    batch = telemetry_record_pb2.TelemetryBatch()
                    batch.ParseFromString(buffer)
                    
                    # Map and Combine transformations
                    for event in batch.events:
                        if event.metric_type == 1:  # OP_DURATION_US
                            key = f"{event.operator_name}_{event.tensor_shape}"
                            global_aggregates[key]["total_value"] += event.metric_value
                            global_aggregates[key]["count"] += 1
        except FileNotFoundError:
            print(f"Warning: Telemetry log file '{file_path}' not found. Run model_trainer.py first.")
            return

    # Export unified structured data
    output_csv = "pipeline_analytics_output.csv"
    with open(output_csv, "w", newline="") as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(["operator_signature", "avg_duration_us", "execution_count"])
        
        for signature, metrics in global_aggregates.items():
            avg_duration = metrics["total_value"] / metrics["count"]
            writer.writerow([signature, avg_duration, metrics["count"]])
            
    print(f"[FlumeLite Engine]: Execution complete. Aggregates exported to {output_csv}")

if __name__ == "__main__":
    run_flume_aggregation()
