#pragma once
#include <iostream>
#include <fstream>
#include <vector>
#include <mutex>
#include <chrono>
#include "telemetry_record.pb.h" // Generated by protoc

class TelemetryAgent {
private:
    std::string node_id_;
    telemetry::Framework framework_;
    std::vector<telemetry::TelemetryEvent> buffer_;
    std::mutex mutex_;
    size_t batch_threshold_;
    std::ofstream out_stream_;

    void flush_to_disk() {
        if (buffer_.empty()) return;
        
        telemetry::TelemetryBatch batch;
        for (const auto& event : buffer_) {
            *batch.add_events() = event;
        }
        
        // Write size prefix for streaming deserialization
        uint32_t size = batch.ByteSizeLong();
        out_stream_.write(reinterpret_cast<const char*>(&size), sizeof(size));
        batch.SerializeToOstream(&out_stream_);
        
        buffer_.clear();
    }

public:
    TelemetryAgent(const std::string& node_id, telemetry::Framework framework, size_t batch_threshold = 1000)
        : node_id_(node_id), framework_(framework), batch_threshold_(batch_threshold) {
        out_stream_.open(node_id_ + "_telemetry.bin", std::ios::binary | std::ios::app);
    }

    ~TelemetryAgent() {
        std::lock_guard<std::mutex> lock(mutex_);
        flush_to_disk();
        if (out_stream_.is_open()) out_stream_.close();
    }

    void record_event(int32_t step_id, const std::string& op_name, 
                      telemetry::MetricType type, double value, const std::string& shape = "") {
        std::lock_guard<std::mutex> lock(mutex_);
        
        telemetry::TelemetryEvent event;
        event.set_timestamp_ns(std::chrono::duration_cast<std::chrono::nanoseconds>(
            std::chrono::system_clock::now().time_since_epoch()).count());
        event.set_node_id(node_id_);
        event.set_step_id(step_id);
        event.set_framework(framework_);
        event.set_operator_name(op_name);
        event.set_metric_type(type);
        event.set_metric_value(value);
        event.set_tensor_shape(shape);

        buffer_.push_back(event);

        if (buffer_.size() >= batch_threshold_) {
            flush_to_disk();
        }
    }
};
