# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry_record.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'telemetry_record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16telemetry_record.proto\x12\ttelemetry\"\xe0\x01\n\x0eTelemetryEvent\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x03\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x0f\n\x07step_id\x18\x03 \x01(\x05\x12\'\n\tframework\x18\x04 \x01(\x0e\x32\x14.telemetry.Framework\x12\x15\n\roperator_name\x18\x05 \x01(\t\x12*\n\x0bmetric_type\x18\x06 \x01(\x0e\x32\x15.telemetry.MetricType\x12\x14\n\x0cmetric_value\x18\x07 \x01(\x01\x12\x14\n\x0ctensor_shape\x18\x08 \x01(\t\";\n\x0eTelemetryBatch\x12)\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x19.telemetry.TelemetryEvent*<\n\tFramework\x12\x19\n\x15\x46RAMEWORK_UNSPECIFIED\x10\x00\x12\x0b\n\x07PYTORCH\x10\x01\x12\x07\n\x03JAX\x10\x02*q\n\nMetricType\x12\x16\n\x12METRIC_UNSPECIFIED\x10\x00\x12\x12\n\x0eOP_DURATION_US\x10\x01\x12\x1b\n\x17MEMORY_ALLOCATION_BYTES\x10\x02\x12\x1a\n\x16\x43OMMUNICATION_DELAY_US\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEWORK']._serialized_start=325
  _globals['_FRAMEWORK']._serialized_end=385
  _globals['_METRICTYPE']._serialized_start=387
  _globals['_METRICTYPE']._serialized_end=500
  _globals['_TELEMETRYEVENT']._serialized_start=38
  _globals['_TELEMETRYEVENT']._serialized_end=262
  _globals['_TELEMETRYBATCH']._serialized_start=264
  _globals['_TELEMETRYBATCH']._serialized_end=323
# @@protoc_insertion_point(module_scope)
